### ISSUE TITLE
Import a mod will cause error

### ISSUE THREAD

**Issue by OkazakiNaoki** [Brachi/albam#40]
### Game
Resident Evil 5 Gold Edition
### Example game file names
uPl07RebeccaNormal.arc

### Blender version
2.78c

### Albam version
0.2.0

### Observed behavior
Modded model is not show up and show up the original model instead.
http://i.imgur.com/kn6kgYA.png
(vertex array length is -58 wow)

### Expected behavior
should at least show the skirt of cheerleader?
http://i.imgur.com/mU8HnZG.png

### Steps to reproduce
Get the mod here:
http://residentevilmodding.boards.net/thread/5839/rebecca-chambers-sports-outfit
Then just import the only arc file in that rar.

**Comment by Brachi** [comment]
Thanks for the report. 
This is a mod from Resident Evil Zero and not an original game file. Unfortunately, the script this mod was created with (I assume [this one](residentevilmodding.boards.net/thread/1504/re5-mod-tool)) does some hacks I didn't have time to investigate yet. But if it works in game, should be supported, of course.

**Comment by Brachi** [comment]
Ok, reading again the script from 3ds max, it states very clear that this is a limitation on the 3ds script. So until that is changed, I don't plan to support this. Closing.
> Limitations:
> - ***very important*** Script cannot import mod file that was exported by this same  script itself. This is due to exported mod file can contain >32 bones map.
