### ISSUE TITLE
Exporting: Original model deformed after export

### ISSUE THREAD

**Issue by knabsi** [Brachi/albam#47]
### Game

Resident Evil 5

### Example game file names

uPl00ChrisNormal.arc
uPl00ChrisCos1.arc

### Blender version

2.78

### Albam version

0.3-testing

### Observed behavior

Model is deformed, finger and eye placement doesn't match, neck is streched after export.
![comparison](https://user-images.githubusercontent.com/31842577/30284833-5975937e-971c-11e7-9917-cc3c483d047a.jpg)

### Expected behavior

Model should be the same as the original.

### Steps to reproduce

Import a model and export without changes.

**Comment by Brachi** [comment]
Thanks for the report.
I fixed it. Can you test it downloading this branch?
https://github.com/Brachi/albam/archive/bugfix/ISSUE-47-original-model-deformed-after-export.zip

This is not the same zip as the release one. Unzip it, then zip the 'albam' folder inside, and that's the one you install.
