### ISSUE TITLE
Exporting: Blender crash

### ISSUE THREAD

**Issue by knabsi** [Brachi/albam#49]
### Game

Resident Evil 5

### Example game file names

uPl02JillCos2.arc

### Blender version

2.79

### Albam version

0.3.0-testing

### Observed behavior

Blender crashes when exporting.

### Expected behavior

Error message should come up.

### Steps to reproduce

Download:
[crash.zip](https://github.com/Brachi/albam/files/1307565/crash.zip)
then click export.

**Comment by Brachi** [comment]
I can't open the zip file, can you double check it?

**Comment by knabsi** [comment]
Weird, I can open it.

**Comment by Brachi** [comment]
Oh, it was a rar with a zip extension.

**Comment by Brachi** [comment]
Fixed in [Albam Reloaded](https://github.com/henryofcarim/albam_reloaded) and backported to Albam.
