### ISSUE TITLE
Exported model streches ingame

### ISSUE THREAD

**Issue by knabsi** [Brachi/albam#50]
### Game

Resident Evil 5

### Example game file names

Any .arc

### Blender version

2.79

### Albam version

0.3.0-testing (albam-bugfix-ISSUE-47-original-model-deformed-after-export)

### Observed behavior

Model streches ingame.
![20170920000432_1](https://user-images.githubusercontent.com/31842577/30619437-aed468ca-9d9f-11e7-999c-155cb23db6e9.jpg)

### Expected behavior

Model should appear normally.

### Steps to reproduce

Export a model that's taller than the original model.

**Comment by Brachi** [comment]
Like we talked, this is due to the model stepping out of the original bounding box.
To solve this, I will make the original bounding box visible and editable, so if the new character has any vertex that needs to go outside the bounding box, the bounding box can be edited to allow it.

**Comment by Brachi** [comment]
@knabsi this is the first working version of the fix: https://github.com/Brachi/albam/archive/bugfix/ISSUE-50-model-stretches.zip
Let me know if it works for you.

Now, every mod that is imported has a visible bounding box. If the mod requires more room in any axis, simple scale the bounding box in edit mode.
The test I made:
1- Scale Chris' head by 3, move it 0.2 units in the Z axis. See that the head is outside of the bounding box, export it. See that it looks stretched in-game
2 - Go back and edit the bounding box in the z axis, so the head is inside the bounding box. Export again. See that the head in-game looks like the on in Blender, not stretched.

## With no bounding box adjustment:
![issue-50-before](https://user-images.githubusercontent.com/6393834/31058989-b46cf788-a6d3-11e7-81c5-1c409382c27b.jpg)

## With bounding box adjustment:
![issue-50-after](https://user-images.githubusercontent.com/6393834/31058994-c115c5b4-a6d3-11e7-8aef-8a9d35fd2a64.jpg)
![untitled](https://user-images.githubusercontent.com/6393834/31059011-ed383be0-a6d3-11e7-9d86-158b96702792.png)
