### ISSUE TITLE
Exporting : ChrisCos4 cannot be exported

### ISSUE THREAD

**Issue by Giant-Soldier** [Brachi/albam#58]
### Game
Resident Evil 5
### Example game file names

ChrisCos4.arc
### Blender version

2.76b
### Albam version
0.3.0-testing

### Observed behavior
The model, even clean, cannot be exported
### Expected behavior
The model could be exported
### Steps to reproduce
Import ChrisCos4.arc , even if you dont do any modification, try to re-export it, the program will not let you do it

**Comment by Brachi** [comment]
Is this from Gold Edition?

**Comment by craftyplumbob** [comment]
Does the Gold Edition off Steam not work with albam? I recently purchased it hoping to take a crack at modding.

**Comment by Brachi** [comment]
@craftyplumbob I haven't tested it myself, but most files from Gold Edition should work. Did you try it

**Comment by Brachi** [comment]
@JacobMrox why you say it works best with 2.8?

**Comment by Brachi** [comment]
Fixed in [Albam Reloaded](https://github.com/henryofcarim/albam_reloaded) and backported to Albam.
