### ISSUE TITLE
Import / Export Errors on recent versions + below 2.78 + Blender 2.8

### ISSUE THREAD

**Issue by JacobMrox** [Brachi/albam#60]
### Game
Resident Evil 5

### Example game file names
Every Upl ARC file.

### Blender version
Below 2.78 and Blender 2.8

### Albam version
0.3.0

### Observed behavior
I think the description should say 2.78 and above because I tried with 2.70 and below 2.78 and all of them had issues which make the plugin unusable on these versions, later versions told me the plugin is made for 2.78 - which the plugin works fine on.

Trying it on the upcoming Blender 2.8 (experimental builds) and there seems no issue on import at all but an error is given on export.

### Expected behavior
It should export fine without errors (but I don't expect it to import/export on versions below 2.78).
But export bug should be fixed for future Blender (2.8) releases perhaps.

**Comment by Brachi** [comment]
Can you post a screenshot of the error you are getting? Where did you get the Albam version installed?

**Comment by JacobMrox** [comment]
Here's the import error on 2.8
https://imgur.com/a/5eju5pa

While the plugin works fine with Blender 2.78 for simple mesh/texture mods, I don't suppose you're supposed to use it for serious mods right? because there is another error I encounter a lot when trying to do so:
https://imgur.com/a/TIF1atC

Here are the steps I did:
Import Jill Cos 4 (BSAA Jill from LIN)
Delete head mesh and head bones
Import Jill Cos 2
Delete body mesh and bones
Merge Jill Cos 2 head bones with Jill Cos 4 bones
Now the Jill Cos 2 head mesh and bones are parented correctly to Jill Cos 4 and its all one skeleton
Just in case I parent the head meshes to Jill Cos 4 skeleton (with Armature Deform, since I assume the wieghts are already there) and the rigging seems fine.
Export and I get the above error...

**Comment by Brachi** [comment]
I see from the first screenshot that they change the Python API. It surprises me since that would break a lot of scripts. The fix should be easy, but I won't dedicate time to it for now, since it's clearly unstable, and might change again in the future.

Regarding the second issue, I can see what happened. It would be much faster for me to fix this if you provide the .blend file. Can you do that?

**Comment by Brachi** [comment]
Checking the blend file it seems the reason of this error is the same as #46.
That model has meshes with no faces, and it fails. I *might* have time soon to fix it. If you want to practice, I recommend starting with uPlChrisNormal, which is the model I did most of my test with.

**Comment by JacobMrox** [comment]
Alright thanks, I'll keep an eye on updates!

**Comment by Brachi** [comment]
Fixed in [Albam Reloaded](https://github.com/henryofcarim/albam_reloaded) and backported to Albam.
