### ISSUE TITLE
5-3 cutscene Wesker invisible (except head) when exported

### ISSUE THREAD

**Issue by JackCeck** [Brachi/albam#62]
### Observed behavior
After doing any edit to Wesker his body appears invisible in the 5-3 cutscene. In gameplay it's fine.

Additionally, the originally intended model appears for a split second, possibly suggesting is a LOD issue.
### Expected behavior
The body should show.

### Steps to reproduce
Import and export Wesker.
![20200721192200_1](https://user-images.githubusercontent.com/68468850/88120423-d8211f80-cb90-11ea-8cd5-a408f982654a.jpg)
![20200721192203_1](https://user-images.githubusercontent.com/68468850/88120426-d8211f80-cb90-11ea-914d-fb3252b841ed.jpg)
![20200721165614_1](https://user-images.githubusercontent.com/68468850/88120427-d8211f80-cb90-11ea-82cf-e63f08f03d6e.jpg)

**Comment by Brachi** [comment]
Fixed in [Albam Reloaded](https://github.com/henryofcarim/albam_reloaded) and backported to Albam.
